# TCL File Generated by Component Editor 18.1
# Mon Nov 27 02:06:52 MSK 2023
# DO NOT MODIFY


# 
# test_pattern_generator_ciris "test_pattern_generator_ciris" v1.0
#  2023.11.27.02:06:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module test_pattern_generator_ciris
# 
set_module_property DESCRIPTION ""
set_module_property NAME test_pattern_generator_ciris
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CIRIS/VIP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME test_pattern_generator_ciris
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL test_pattern_generator_ciris_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alt_vipvfr131_common_control_packet_encoder.v VERILOG PATH ../../../common/common_lib2/AvalonST/crs_av_st_output/rtl/alt_vipvfr131_common_stream_output.v
add_fileset_file alt_vipvfr131_common_stream_output.v VERILOG PATH ../../../common/common_lib2/AvalonST/crs_av_st_output/rtl/alt_vipvfr131_common_stream_output.v
add_fileset_file av_univ_regs.sv SYSTEM_VERILOG PATH ../../../common/common_lib/rtl/av_univ_regs.sv
add_fileset_file mux_test_pattern_generator_ciris.sv SYSTEM_VERILOG PATH rtl/mux_test_pattern_generator_ciris.sv
add_fileset_file test_pattern_generator_ciris.sv SYSTEM_VERILOG PATH rtl/test_pattern_generator_ciris.sv
add_fileset_file test_pattern_generator_ciris_top.sv SYSTEM_VERILOG PATH rtl/test_pattern_generator_ciris_top.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES {3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter SYMBOLS_PER_BEAT INTEGER 3
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 3
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES {3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 24
set_parameter_property DATA_WIDTH DEFAULT_VALUE 24
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter INTERLACED INTEGER 3
set_parameter_property INTERLACED DEFAULT_VALUE 3
set_parameter_property INTERLACED DISPLAY_NAME INTERLACED
set_parameter_property INTERLACED TYPE INTEGER
set_parameter_property INTERLACED UNITS None
set_parameter_property INTERLACED ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INTERLACED HDL_PARAMETER true
add_parameter HEIGHT INTEGER 600
set_parameter_property HEIGHT DEFAULT_VALUE 600
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT TYPE INTEGER
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES {350 400 480 576 600 768 800 864 960 1024 1050 1200 1344 1392 1440}
set_parameter_property HEIGHT HDL_PARAMETER true
add_parameter WIDTH INTEGER 800
set_parameter_property WIDTH DEFAULT_VALUE 800
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES {640 720 768 800 1024 1152 1280 1368 1400 1440 1600 1680 1792 1856 1920}
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter MODE_BW INTEGER 0
set_parameter_property MODE_BW DEFAULT_VALUE 0
set_parameter_property MODE_BW DISPLAY_NAME MODE_BW
set_parameter_property MODE_BW TYPE INTEGER
set_parameter_property MODE_BW UNITS None
set_parameter_property MODE_BW ALLOWED_RANGES {0 1}
set_parameter_property MODE_BW HDL_PARAMETER true
add_parameter OFFSET_FRAMES INTEGER 25
set_parameter_property OFFSET_FRAMES DEFAULT_VALUE 25
set_parameter_property OFFSET_FRAMES DISPLAY_NAME OFFSET_FRAMES
set_parameter_property OFFSET_FRAMES TYPE INTEGER
set_parameter_property OFFSET_FRAMES UNITS None
set_parameter_property OFFSET_FRAMES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OFFSET_FRAMES HDL_PARAMETER true
add_parameter MODE INTEGER 1
set_parameter_property MODE DEFAULT_VALUE 1
set_parameter_property MODE DISPLAY_NAME MODE
set_parameter_property MODE TYPE INTEGER
set_parameter_property MODE UNITS None
set_parameter_property MODE ALLOWED_RANGES {0 1 2 3 4}
set_parameter_property MODE HDL_PARAMETER true
add_parameter LATENCY STRING ON
set_parameter_property LATENCY DEFAULT_VALUE ON
set_parameter_property LATENCY DISPLAY_NAME LATENCY
set_parameter_property LATENCY TYPE STRING
set_parameter_property LATENCY UNITS None
set_parameter_property LATENCY HDL_PARAMETER true
add_parameter AVALON_MM STRING OFF
set_parameter_property AVALON_MM DEFAULT_VALUE OFF
set_parameter_property AVALON_MM DISPLAY_NAME AVALON_MM
set_parameter_property AVALON_MM TYPE STRING
set_parameter_property AVALON_MM UNITS None
set_parameter_property AVALON_MM HDL_PARAMETER true
add_parameter DW INTEGER 32
set_parameter_property DW DEFAULT_VALUE 32
set_parameter_property DW DISPLAY_NAME DW
set_parameter_property DW TYPE INTEGER
set_parameter_property DW UNITS None
set_parameter_property DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DW HDL_PARAMETER true
add_parameter AW INTEGER 16
set_parameter_property AW DEFAULT_VALUE 16
set_parameter_property AW DISPLAY_NAME AW
set_parameter_property AW TYPE INTEGER
set_parameter_property AW UNITS None
set_parameter_property AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AW HDL_PARAMETER true
add_parameter REGS_NUM INTEGER 4
set_parameter_property REGS_NUM DEFAULT_VALUE 4
set_parameter_property REGS_NUM DISPLAY_NAME REGS_NUM
set_parameter_property REGS_NUM TYPE INTEGER
set_parameter_property REGS_NUM UNITS None
set_parameter_property REGS_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REGS_NUM HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avms
# 
add_interface avms avalon end
set_interface_property avms addressUnits WORDS
set_interface_property avms associatedClock clock_sink
set_interface_property avms associatedReset reset_sink
set_interface_property avms bitsPerSymbol 8
set_interface_property avms burstOnBurstBoundariesOnly false
set_interface_property avms burstcountUnits WORDS
set_interface_property avms explicitAddressSpan 0
set_interface_property avms holdTime 0
set_interface_property avms linewrapBursts false
set_interface_property avms maximumPendingReadTransactions 0
set_interface_property avms maximumPendingWriteTransactions 0
set_interface_property avms readLatency 0
set_interface_property avms readWaitTime 1
set_interface_property avms setupTime 0
set_interface_property avms timingUnits Cycles
set_interface_property avms writeWaitTime 0
set_interface_property avms ENABLED true
set_interface_property avms EXPORT_OF ""
set_interface_property avms PORT_NAME_MAP ""
set_interface_property avms CMSIS_SVD_VARIABLES ""
set_interface_property avms SVD_ADDRESS_GROUP ""

add_interface_port avms avms_address address Input AW
add_interface_port avms avms_byteenable byteenable Input DW/8
add_interface_port avms avms_read read Input 1
add_interface_port avms avms_write write Input 1
add_interface_port avms avms_writedata writedata Input DW
add_interface_port avms avms_readdata readdata Output DW
set_interface_assignment avms embeddedsw.configuration.isFlash 0
set_interface_assignment avms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avms embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data_o data Output DATA_WIDTH
add_interface_port avalon_streaming_source eop_o endofpacket Output 1
add_interface_port avalon_streaming_source ready_i ready Input 1
add_interface_port avalon_streaming_source sop_o startofpacket Output 1
add_interface_port avalon_streaming_source valid_o valid Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset_n Input 1

