onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_test_pattern_generator_ciris/clk_i
add wave -noupdate /tb_test_pattern_generator_ciris/rst_i
add wave -noupdate /tb_test_pattern_generator_ciris/ready_i
add wave -noupdate /tb_test_pattern_generator_ciris/valid_o
add wave -noupdate /tb_test_pattern_generator_ciris/enable
add wave -noupdate /tb_test_pattern_generator_ciris/data_o
add wave -noupdate /tb_test_pattern_generator_ciris/height
add wave -noupdate /tb_test_pattern_generator_ciris/width
add wave -noupdate /tb_test_pattern_generator_ciris/interlaced
add wave -noupdate /tb_test_pattern_generator_ciris/offset_frames
add wave -noupdate /tb_test_pattern_generator_ciris/color_onecolor
add wave -noupdate /tb_test_pattern_generator_ciris/mode_bw
add wave -noupdate /tb_test_pattern_generator_ciris/end_of_video_o
add wave -noupdate /tb_test_pattern_generator_ciris/data_stndrt_o
add wave -noupdate /tb_test_pattern_generator_ciris/data_offset_o
add wave -noupdate /tb_test_pattern_generator_ciris/data_grad_o
add wave -noupdate /tb_test_pattern_generator_ciris/data_onecolor_o
add wave -noupdate /tb_test_pattern_generator_ciris/data_image_o
add wave -noupdate /tb_test_pattern_generator_ciris/avms_address
add wave -noupdate /tb_test_pattern_generator_ciris/avms_byteenable
add wave -noupdate /tb_test_pattern_generator_ciris/avms_read
add wave -noupdate /tb_test_pattern_generator_ciris/avms_readdata
add wave -noupdate /tb_test_pattern_generator_ciris/avms_write
add wave -noupdate /tb_test_pattern_generator_ciris/avms_writedata
add wave -noupdate /tb_test_pattern_generator_ciris/word_valid_wr_o
add wave -noupdate /tb_test_pattern_generator_ciris/word
add wave -noupdate /tb_test_pattern_generator_ciris/slv_word_i
add wave -noupdate /tb_test_pattern_generator_ciris/word_valid_rd_o
add wave -noupdate /tb_test_pattern_generator_ciris/vip_ctrl_send_o
add wave -noupdate /tb_test_pattern_generator_ciris/count_1
add wave -noupdate /tb_test_pattern_generator_ciris/count_2
add wave -noupdate /tb_test_pattern_generator_ciris/f
add wave -noupdate /tb_test_pattern_generator_ciris/count_3
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/clk_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/rst_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/ready_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/enable
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/mode_bw_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/height_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/width_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/interlaced_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/offset_frames_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/color_onecolor_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/valid_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/end_of_video_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_stndrt_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_offset_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_grad_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_onecolor_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_imag_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/interlaced_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/vip_ctrl_send_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/cnt_line
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/cnt_stripe
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/cnt_offset
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/grad_reg_color
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/grad_reg_bw
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/width_reg
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/heght_reg
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_stndrt
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_offset
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_grad
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_grad_bw
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_grad_color
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_onecolor
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/data_reg_image
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/coef_c
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/coef_b
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/coef_a
add wave -noupdate /tb_test_pattern_generator_ciris/uut_gen_polos/color_states
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/clk_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/reset_n_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_address
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_byteenable
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_read
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_readdata
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_write
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_writedata
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/word_valid_wr_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/mst_word_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/slv_word_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/word_valid_rd_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/mst_regs_av
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/slv_regs_av
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/byte_valid_wr
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/byte_valid_rd
add wave -noupdate /tb_test_pattern_generator_ciris/uut_av_univ_regs/avms_writedata_bytes
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/clk_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/rst_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/word_valid_wr_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/word_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/word_valid_rd_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_stndrt_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_offset_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_grad_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_onecolor_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_image_i
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/data_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/enable_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/mode_bw_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/height_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/width_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/offset_frames_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/interlaced_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/color_onecolor_o
add wave -noupdate /tb_test_pattern_generator_ciris/uut_mux_gen/reg_mode
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {59604 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 421
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {845 ps}
